### ISSUE TITLE
`db.collection()` returns error

### ISSUE THREAD

**Issue by josephhuxley** [vincentdchan/PoloDB#34]
Cannot use `db.collection()` to select a collection to insert into using the Python wrapper
```
Traceback (most recent call last):
  File "test_db.py", line 32, in <module>
    test_create_collection()
  File "test_db.py", line 16, in test_create_collection
    collection = db.collection('test')
SystemError: <method 'collection' of 'polodb.Database' objects> returned NULL without setting an error
```

code:
`collection = db.collection('test')`

**Comment by vincentdchan** [comment]
Are you creating a new database, or working on an exist database?

**Comment by josephhuxley** [comment]
existing database

**Comment by vincentdchan** [comment]
Will be fixed today, which platform are you using?

**Comment by vincentdchan** [comment]
Fixed. Try [0.8.1](https://pypi.org/project/polodb/0.8.1/)

**Comment by josephhuxley** [comment]
Great!
